services:
  db:
    image: postgres:11.12
    environment:
      POSTGRES_USER: export
      POSTGRES_PASSWORD: export
      POSTGRES_DB: export
    ports:
      - 15432:5432

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: sqs
      HOSTNAME: localstack
      HOSTNAME_EXTERNAL: localstack
      DEFAULT_REGION: us-east-1
    ports:
      - 4566:4566

  web:
    build: &docker_build
      context: .
      args:
        SSH_DEPLOYMENT_KEY: ${SSH_DEPLOYMENT_KEY:-}
    restart: unless-stopped
    command: python main.py
    environment: &docker_environment
      SQLALCHEMY_DB_URI: postgresql+asyncpg://export:export@db/export
      AWS_ACCESS_KEY_ID: FAKE
      AWS_SECRET_ACCESS_KEY: FAKE
      AWS_DEFAULT_REGION: us-east-1
      AWS_SQS_ENDPOINT_URL: http://localstack:4566
      CELERY_BROKER_QUEUE: http://localstack:4566/000000000000/export
    volumes: &docker_volumes
      - .:/app
    ports:
      - 8000:8000

  worker:
    build: *docker_build
    restart: unless-stopped
    command: celery -A app worker
    environment: *docker_environment
    volumes: *docker_volumes
