"""Init

Revision ID: 35c27e44887c
Revises:
Create Date: 2021-12-30 12:33:20.397479

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "35c27e44887c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report",
        sa.Column("filter_input", sa.JSON(), nullable=True),
        sa.Column("columns", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_report_created_at"), "report", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_report_id"), "report", ["id"], unique=False)
    op.create_index(op.f("ix_report_scope"), "report", ["scope"], unique=False)
    op.create_index(op.f("ix_report_type"), "report", ["type"], unique=False)
    op.create_index(
        op.f("ix_report_updated_at"), "report", ["updated_at"], unique=False
    )
    op.create_table(
        "Job",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content_file", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cursor", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Job_content_file"), "Job", ["content_file"], unique=False)
    op.create_index(op.f("ix_Job_created_at"), "Job", ["created_at"], unique=False)
    op.create_index(op.f("ix_Job_cursor"), "Job", ["cursor"], unique=False)
    op.create_index(op.f("ix_Job_id"), "Job", ["id"], unique=False)
    op.create_index(op.f("ix_Job_report_id"), "Job", ["report_id"], unique=False)
    op.create_index(op.f("ix_Job_status"), "Job", ["status"], unique=False)
    op.create_index(op.f("ix_Job_updated_at"), "Job", ["updated_at"], unique=False)
    op.create_table(
        "exportevent",
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("export_file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["export_file_id"],
            ["Job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exportevent_date"), "exportevent", ["date"], unique=False)
    op.create_index(
        op.f("ix_exportevent_export_file_id"),
        "exportevent",
        ["export_file_id"],
        unique=False,
    )
    op.create_index(op.f("ix_exportevent_id"), "exportevent", ["id"], unique=False)
    op.create_index(op.f("ix_exportevent_type"), "exportevent", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exportevent_type"), table_name="exportevent")
    op.drop_index(op.f("ix_exportevent_id"), table_name="exportevent")
    op.drop_index(op.f("ix_exportevent_export_file_id"), table_name="exportevent")
    op.drop_index(op.f("ix_exportevent_date"), table_name="exportevent")
    op.drop_table("exportevent")
    op.drop_index(op.f("ix_Job_updated_at"), table_name="Job")
    op.drop_index(op.f("ix_Job_status"), table_name="Job")
    op.drop_index(op.f("ix_Job_report_id"), table_name="Job")
    op.drop_index(op.f("ix_Job_id"), table_name="Job")
    op.drop_index(op.f("ix_Job_cursor"), table_name="Job")
    op.drop_index(op.f("ix_Job_created_at"), table_name="Job")
    op.drop_index(op.f("ix_Job_content_file"), table_name="Job")
    op.drop_table("Job")
    op.drop_index(op.f("ix_report_updated_at"), table_name="report")
    op.drop_index(op.f("ix_report_type"), table_name="report")
    op.drop_index(op.f("ix_report_scope"), table_name="report")
    op.drop_index(op.f("ix_report_id"), table_name="report")
    op.drop_index(op.f("ix_report_created_at"), table_name="report")
    op.drop_table("report")
    # ### end Alembic commands ###
