"""Create file and event tables

Revision ID: 7190f67daae2
Revises: 
Create Date: 2021-12-15 11:16:42.198337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7190f67daae2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'DELETED', name='jobstatusesenum'), nullable=True),
    sa.Column('type', sa.Enum('PRODUCTS', 'ORDERS', name='exportfiletypesenum'), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.Column('content_file', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.Enum('EXPORT_PENDING', 'EXPORT_SUCCESS', 'EXPORT_FAILED', 'EXPORT_DELETED', 'EXPORTED_FILE_SENT', 'EXPORT_FAILED_INFO_SENT', name='exporteventsenum'), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('export_file_id', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['export_file_id'], ['export_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('export_event')
    op.drop_table('export_file')
    # ### end Alembic commands ###
