"""Init

Revision ID: 727196644035
Revises:
Create Date: 2021-12-16 20:00:28.284323

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "727196644035"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report",
        sa.Column("filter_input", sa.JSON(), nullable=True),
        sa.Column("ids", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_report_created_at"), "report", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_report_id"), "report", ["id"], unique=False)
    op.create_index(op.f("ix_report_scope"), "report", ["scope"], unique=False)
    op.create_index(op.f("ix_report_type"), "report", ["type"], unique=False)
    op.create_index(
        op.f("ix_report_updated_at"), "report", ["updated_at"], unique=False
    )
    op.create_table(
        "exportfile",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_file", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exportfile_content_file"), "exportfile", ["content_file"], unique=False
    )
    op.create_index(
        op.f("ix_exportfile_created_at"), "exportfile", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_exportfile_id"), "exportfile", ["id"], unique=False)
    op.create_index(
        op.f("ix_exportfile_message"), "exportfile", ["message"], unique=False
    )
    op.create_index(
        op.f("ix_exportfile_report_id"), "exportfile", ["report_id"], unique=False
    )
    op.create_index(
        op.f("ix_exportfile_status"), "exportfile", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_exportfile_updated_at"), "exportfile", ["updated_at"], unique=False
    )
    op.create_table(
        "exportevent",
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("export_file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["export_file_id"],
            ["exportfile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exportevent_date"), "exportevent", ["date"], unique=False)
    op.create_index(
        op.f("ix_exportevent_export_file_id"),
        "exportevent",
        ["export_file_id"],
        unique=False,
    )
    op.create_index(op.f("ix_exportevent_id"), "exportevent", ["id"], unique=False)
    op.create_index(op.f("ix_exportevent_type"), "exportevent", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exportevent_type"), table_name="exportevent")
    op.drop_index(op.f("ix_exportevent_id"), table_name="exportevent")
    op.drop_index(op.f("ix_exportevent_export_file_id"), table_name="exportevent")
    op.drop_index(op.f("ix_exportevent_date"), table_name="exportevent")
    op.drop_table("exportevent")
    op.drop_index(op.f("ix_exportfile_updated_at"), table_name="exportfile")
    op.drop_index(op.f("ix_exportfile_status"), table_name="exportfile")
    op.drop_index(op.f("ix_exportfile_report_id"), table_name="exportfile")
    op.drop_index(op.f("ix_exportfile_message"), table_name="exportfile")
    op.drop_index(op.f("ix_exportfile_id"), table_name="exportfile")
    op.drop_index(op.f("ix_exportfile_created_at"), table_name="exportfile")
    op.drop_index(op.f("ix_exportfile_content_file"), table_name="exportfile")
    op.drop_table("exportfile")
    op.drop_index(op.f("ix_report_updated_at"), table_name="report")
    op.drop_index(op.f("ix_report_type"), table_name="report")
    op.drop_index(op.f("ix_report_scope"), table_name="report")
    op.drop_index(op.f("ix_report_id"), table_name="report")
    op.drop_index(op.f("ix_report_created_at"), table_name="report")
    op.drop_table("report")
    # ### end Alembic commands ###
