"""Add recipients

Revision ID: dd5629eac406
Revises: 75d442069718
Create Date: 2022-01-09 21:34:51.920774

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "dd5629eac406"
down_revision = "75d442069718"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("report", sa.Column("recipients", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report", "recipients")
    # ### end Alembic commands ###
