name: Deploy to staging
on:
  push:
    branches:
      - develop
      - ci/**

jobs:
  build_and_deploy:
    if: github.repository_owner == 'saleor'
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      AWS_ACCOUNT: "727618530289"
      AWS_REGION: us-east-1
      AWS_STATICS_BUCKET: saleor-apps-public-us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup environment
        run: |
          BUILD_TAG=git-$(git rev-parse --short "$GITHUB_SHA")
          echo "BUILD_TAG=${BUILD_TAG}" >> $GITHUB_ENV

          IMAGE_REPO=${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/saleor-apps-export
          echo "IMAGE_TAGS=${IMAGE_REPO}:${BUILD_TAG},${IMAGE_REPO}:staging" >> $GITHUB_ENV
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_APPS_STAGING_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_APPS_STAGING_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build statics
        working-directory: ./ui
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SALEOR_APP_UI_DEPLOYMENT_KEY }}" > ~/.ssh/saleor-app-ui
          chmod 400 ~/.ssh/saleor-app-ui
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/saleor-app-ui

          npm install
          npm run build
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push container
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: docker/prod.Dockerfile
          push: True
          tags: ${{ env.IMAGE_TAGS }}
          build-args: |
            "SSH_DEPLOYMENT_KEY=${{ secrets.SALEOR_APP_BASE_DEPLOYMENT_KEY }}"
      - name: Deploy statics
        working-directory: ./ui
        run: |
          aws s3 sync build s3://${AWS_STATICS_BUCKET}/export/staging --delete
          aws s3 sync build s3://${AWS_STATICS_BUCKET}/export/${BUILD_TAG} --delete
